Makefile: run clean-* before install-ddr-* tasks
This should prevent the
"AttributeError: 'module' object has no attribute 'config'"
errors when repo_models/*.py modules try to refer to
converters.config caused (I think) by old build files hanging
around.